language: node_js
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  fqdn: donnakevin.wedding
  on:
    branch: master
