version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "donnakevin-wedding"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fmleitzrf9yn"
s3_prefix = "donnakevin-wedding"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
