AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  donnakevin.wedding

  Lambda functions for the wedding website

Globals:
  Function:
    Runtime: nodejs14.x
    Handler: index.handler
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Accept,Content-Type'"

Resources:
  RsvpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: rsvp/
      Events:
        Rsvp:
          Type: Api
          Properties:
            Path: /rsvp
            Method: post
      Policies:
        - SESCrudPolicy: { IdentityName: donnakevin.wedding }
        - SESCrudPolicy: { IdentityName: kevindew@me.com }
        - SESCrudPolicy: { IdentityName: donna.carter72@yahoo.com }

  GiftFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gift/
      Environment:
        Variables:
          STRIPE_API_KEY: '{{resolve:secretsmanager:donnakevin.wedding:SecretString:STRIPE_API_KEY}}'
      Events:
        Rsvp:
          Type: Api
          Properties:
            Path: /gift
            Method: post

Outputs:
  RsvpApi:
    Description: "API Gateway endpoint URL for RSVP function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rsvp/"
  RsvpFunction:
    Description: "RSVP Lambda Function ARN"
    Value: !GetAtt RsvpFunction.Arn
  RsvpFunctionIamRole:
    Description: "Implicit IAM Role created for RSVP function"
    Value: !GetAtt RsvpFunctionRole.Arn
  GiftApi:
    Description: "API Gateway endpoint URL for gift function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/gift/"
  GiftFunction:
    Description: "Gift Lambda Function ARN"
    Value: !GetAtt GiftFunction.Arn
  GiftFunctionIamRole:
    Description: "Implicit IAM Role created for gift function"
    Value: !GetAtt GiftFunctionRole.Arn
