on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Test RSVP function
        working-directory: lambda/rsvp
        run: |
          npm ci
          npm test
      - name: Test Gift function
        working-directory: lambda/gift
        run: |
          npm ci
          npm test
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
